import { Graphics } from "@/src-client/components/Graphics";
import NavBar from "@/src-client/components/NavBar";

import Head from "next/head";
import PersonalFinances from "./personal";

export default function Home() {
  return (
    <>
      <Head>
        <title>Personal Finance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container-graphics">
          <PersonalFinances />
        </div>
      </main>
    </>
  );
}
