import { Graphics } from "@/src-client/components/Graphics";
import NavBar from "@/src-client/components/NavBar";
import { TableComponent } from "@/src-client/components/Tables/TableComponent";
import { Inter } from "next/font/google";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Personal Finance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar page="home" />
        <div>
          <Graphics />
        </div>
      </main>
    </>
  );
}
